version: '3.7'

services:
    nginx:
        build:
            context: ./.docker/services
            dockerfile: ./nginx/build/Dockerfile
        container_name: nginx
        command: [/bin/bash, .docker/services/nginx/build/command.sh]
        ports:
            - 443:443
        volumes:
            - ./.docker/services/nginx/conf:/etc/nginx/conf.d
            - .:/var/www/app
        volumes_from: 
            - api

    api:
        build:
            context: ./.docker/services
            dockerfile: ./api/Dockerfile
        container_name: api
        restart: always
        volumes:
            - .:/var/www/app
        command: [/bin/bash, ./.docker/services/api/command.sh]
        env_file: 
            - ./.docker/services/api/.env
        expose:
            - 3000
        depends_on:
            - db
            - redis
        tty: true

    db:
        image: postgres:12-alpine
        container_name: db
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.docker/services/db/.env

    redis:
        image: redis:3.2
        container_name: redis
        volumes:
            - ./.docker/services/redis/data:/data
        
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.30
        restart: always
        env_file:
            - ./.docker/services/pgadmin/.env
        ports:
            - 8080:80
        volumes:
            - pg-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    db-data:
    pg-data:

