version: '3.7'

services:
    nginx:
        build: ./nginx/
        container_name: nginx
        command: [/bin/bash, ./command.sh]
        ports:
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/command.sh:/etc/nginx/command.sh
        volumes_from: 
            - api

    api:
        build: ./api/
        container_name: api
        restart: always
        volumes:
            - ./api:/var/www/app
        command: [/bin/bash, ./command.sh]
        env_file: 
            - ./.env
        expose:
            - 3000
        depends_on:
            - db
            - redis
        tty: true
        stdin_open: true

    cron:
        build: ./cron/
        container_name: cron
        restart: always
        volumes:
            - ./cron:/var/www/cron
        command: [/bin/bash, ./command.sh]
        env_file: 
            - ./.env
        depends_on:
            - db
        tty: true

    db:
        image: postgres:12-alpine
        container_name: db
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env

    redis:
        image: redis:3.2
        container_name: redis
        volumes:
            - ./data/redis:/data
        
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.30
        restart: always
        env_file:
            - ./.env
        ports:
            - 8080:80
        volumes:
            - ./data/pgclient:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
