version: '3.7'

services:
    # nginx:
    #     build: ./docker/nginx/
    #     container_name: nginx
    #     command: [/bin/bash, ./command.sh]
    #     ports:
    #         - 443:443
    #     volumes:
    #         - ./docker/nginx/conf.d:/etc/nginx/conf.d
    #         - ./docker/nginx/certs:/etc/nginx/certs
    #         - ./docker/nginx/command.sh:/etc/nginx/command.sh
    #     depends_on:  
    #         - api

    # bw-webserver:
    #     build: ./bw-webserver/
    #     container_name: bw-webserver
    #     restart: always
    #     volumes:
    #         - ./bw-webserver:/var/www/server
    #     env_file: 
    #         - ./.env
    #     expose:
    #         - 3000
    #     depends_on:
    #         - bw-database
    #     tty: true

    bw-database:
        image: postgres:12-alpine
        container_name: bw-database
        restart: always
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:5.4
        restart: always
        env_file:
            - ./.env
        ports:
            - 8080:80
        links:
            - "bw-database:pgsql-server"
