[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "persistence",
] }
egui = "0.27.2"
env_logger.workspace = true
log.workspace = true
serde = "1.0.203"
